### ISSUE TITLE
Requires Jquery

### ISSUE THREAD

**Issue by DeeEmm** [CelliesProjects/minimalUploadAuthESP32#1]
This is not a minimal implementation as it requires jQuery library, which is also not specified in readme

- Requires external dependency
- Does not work if you do not have an internet connection

Would be better to provide a version without the requirement for jQuery

/DM

**Comment by CelliesProjects** [comment]
That is a valid point.

**Comment by CelliesProjects** [comment]
And this issue should be fixed with 76328e1fc671cadbf47d14f1e4672e94dc6222c3
